# Generated by Django 4.1.2 on 2022-10-28 17:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0005_alter_post_commented_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='commented_users',
            field=models.ManyToManyField(related_name='post_comments', through='posts.Comment', to=settings.AUTH_USER_MODEL, verbose_name='Прокомментировавшие пользователи'),
        ),
        migrations.AlterField(
            model_name='post',
            name='liked_users',
            field=models.ManyToManyField(related_name='liked_posts', to=settings.AUTH_USER_MODEL, verbose_name='Понравилось пользователям'),
        ),
    ]
