# Generated by Django 4.1.2 on 2022-10-28 17:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_account_subscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='subscriptions',
            field=models.ManyToManyField(related_name='subscribers', to=settings.AUTH_USER_MODEL, verbose_name='Подписки'),
        ),
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(default=1, upload_to='avatars', verbose_name='Аватар'),
            preserve_default=False,
        ),
    ]
