# Generated by Django 4.1.2 on 2022-10-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_account_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(blank=True, default=1, upload_to='avatars', verbose_name='Аватар'),
            preserve_default=False,
        ),
    ]
